---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-kubernetes-demo
    group: org.vidi
  name: cloud-kubernetes-demo

spec:
  selector:
    matchLabels:
      app: cloud-kubernetes-demo
      group: org.vidi
  template:
    metadata:
      labels:
        app: cloud-kubernetes-demo
        group: org.vidi
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: development
          name: cloud-kubernetes-demo
          image: vidi/spring-cloud-kubernetes-demo:0.0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /actuator/health/liveness
              scheme: HTTP
            initialDelaySeconds: 100
            successThreshold: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false

