---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-kubernetes-demo
    group: org.vidi
  name: cloud-kubernetes-demo
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: cloud-kubernetes-demo
    group: org.vidi
  type: NodePort

  # cloud-kubernetes-demo.default:8080